apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-producer
  template:
    metadata:
      labels:
        app: rabbitmq-producer
    spec:
      containers:
        - name: rabbitmq-producer
          image: rabbitmq-producer
          imagePullPolicy: IfNotPresent
          env:
            - name: RABBITQM_RELAY_HOST
              value: rabbitmq
            - name: RABBITQM_RELAY_PORT
              value: "5672"
